# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'SwiftApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftApp
  pod 'Fundamental', :path => '../../Library/Fundamental/Fundamental.podspec'
  
  pod 'AppUIKit', :path => '../../Library/AppUIKit/AppUIKit.podspec'
  
  pod 'GoogleAnalytics'
end
